name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  first-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: |
          echo "1st step"
          echo "2nd step"
          echo "3rd step"
