name: Cron Job Workflow

on:
  schedule:
    - cron: "*/2 * * * *" # every 2 minutes

jobs:
  first-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Cron Workflows
        run: |
          echo "Hello cron job"
