name: Build, Test, and Deploy React App

on:
  push:
    branches:
      - main # Trigger this workflow when pushing to the main branch

jobs:
  build:
    name: Build, Test, and Deploy
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use your desired Node.js version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the project
      - name: Build the project
        run: npm run build

      # 5. Run tests
      - name: Run tests
        run: npm test

      # 6. Deploy To Server
      - name: Deploy To Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          # Debug: Check if HOST secret is set properly
          if [ -z "$HOST" ]; then
            echo "Error: HOST is not set"
            exit 1
          else
            echo "HOST is set to $HOST"
          fi

          # Create the .ssh directory if it doesn't exist
          mkdir -p ~/.ssh

          # Save the private key
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add the server to known_hosts
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # Remove existing files and upload the build
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$HOST "rm -rf /var/www/html/*"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r build/* $USER@$HOST:/var/www/html/
