name: Build, Test, and Deploy React App

on:
  push:
    branches:
      - main # Trigger this workflow when pushing to the main branch

jobs:
  build:
    name: Build, Test, and Deploy
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use your desired Node.js version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the project
      - name: Build the project
        run: npm run build

      # 5. Run tests
      - name: Run tests
        run: npm test

      # 6. Deploy to Server
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          # Debug: Check the value of HOST
          echo "HOST is: $HOST"

          # Create the .ssh directory if it doesn't exist
          mkdir -p ~/.ssh

          # Save the private key
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

          # Debug: Check SSH key permissions
          ls -l ~/.ssh

          # Add the server to known hosts
          ssh-keyscan $HOST >> ~/.ssh/known_hosts

          # Remove existing files and upload the build
          ssh -i ~/.ssh/key.pem $USER@$HOST "rm -rf /var/www/html/*"
          scp -i ~/.ssh/key.pem -r build/* $USER@$HOST:/var/www/html/
