name: Deploy React App to AWS

on:
  push:
    branches:
      - main # Trigger this workflow when pushing to the main branch

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-22.04

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use your desired Node.js version

    # 3. Install dependencies and build
    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    # 4. Deploy to AWS
    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1 # Replace with your region
      run: |
        ssh -o StrictHostKeyChecking=no -i "$KEY" $USER@$HOST "rm -rf /var/www/html/*"
        scp -i "$KEY" -r build/* $USER@$HOST:/var/www/html/

